words:
  - compat
  - esbuild
  - nodenext
  - lennondotw
  - Vitest
  - tmpdir
  - outdir
  - outfile
  - homedir
  - subdir
  - olduser
  - newuser
  - testuser
  - myuser
  - targetuser
  - rustup
  - venv
  - pycache
  - virtualenvs
  - fseventsd
  - repositoryformatversion
  - filemode
  - reekystive
flagWords:
  - blacklist -> blocklist
  - whitelist -> allowlist
suggestWords:
  - colour -> color
ignorePaths:
  - cspell.config.yaml
  - pnpm-lock.yaml
  - node_modules
